
export default new Map([
["src/content/blog/combating-legal-ai-hallucinations.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fcombating-legal-ai-hallucinations.mdx&astroContentModuleFlag=true")],
["src/content/blog/hello-world.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhello-world.mdx&astroContentModuleFlag=true")],
["src/content/projects/adp-workforcenow.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fadp-workforcenow.mdx&astroContentModuleFlag=true")],
["src/content/blog/ai-statistics-future-decision-making.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fai-statistics-future-decision-making.mdx&astroContentModuleFlag=true")],
["src/content/blog/building-my-own-local-llm-stack.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fbuilding-my-own-local-llm-stack.mdx&astroContentModuleFlag=true")],
["src/content/projects/advancedmd-implementation.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fadvancedmd-implementation.mdx&astroContentModuleFlag=true")],
["src/content/projects/bank-projections-modeling.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fbank-projections-modeling.mdx&astroContentModuleFlag=true")],
["src/content/projects/ferment-app.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fferment-app.mdx&astroContentModuleFlag=true")],
["src/content/projects/fanalyx-deterministic-finance-platform.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Ffanalyx-deterministic-finance-platform.mdx&astroContentModuleFlag=true")],
["src/content/projects/google-workspace-migration.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fgoogle-workspace-migration.mdx&astroContentModuleFlag=true")],
["src/content/projects/llm-note-coaching.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fllm-note-coaching.mdx&astroContentModuleFlag=true")],
["src/content/projects/microsoft-fabric.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fmicrosoft-fabric.mdx&astroContentModuleFlag=true")]]);
		