allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  esbuild: true
  puppeteer: true
  sharp: true
  workerd: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - esbuild
  - puppeteer
  - sharp
  - workerd

overrides:
  minimatch: "10.2.3"
  rollup: "4.59.0"
  undici: "7.18.2"
  ajv: "8.18.0"
  tmp: "0.2.4"
  lodash: "4.17.23"

peerDependencyRules:
  allowedVersions:
    tailwindcss: 4.3.1
