import type { Config } from 'tailwindcss';
import containerQueries from '@tailwindcss/container-queries';
import typography from '@tailwindcss/typography';

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,mdx}'],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT:
          'clamp(var(--container-padding, 1rem), 4vw, var(--container-padding-lg, 4rem))',
        sm: 'clamp(var(--container-padding-sm, 2rem), 5vw, var(--container-padding-lg, 4rem))',
        lg: 'clamp(var(--container-padding-lg, 4rem), 6vw, var(--container-padding-xl, 5rem))',
        xl: 'clamp(var(--container-padding-xl, 5rem), 7vw, var(--container-padding-2xl, 6rem))',
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1440px',
      },
    },
    extend: {
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(40px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        pulseGlow: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        themeToggleSpin: {
          '100%': { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        fadeIn:
          'fadeIn var(--duration, 250ms) var(--ease-standard, cubic-bezier(0.4,0,0.2,1)) both',
        fadeInUp:
          'fadeInUp var(--duration, 250ms) var(--ease-standard, cubic-bezier(0.4,0,0.2,1)) both',
        slideUp:
          'slideUp var(--duration, 250ms) var(--ease-emphasized, cubic-bezier(0.2,0,0,1)) both',
        float: 'float 3s var(--ease-standard, cubic-bezier(0.4,0,0.2,1)) infinite',
        pulseGlow: 'pulseGlow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        themeToggleSpin:
          'themeToggleSpin var(--duration-fast, 150ms) var(--ease-standard, cubic-bezier(0.4,0,0.2,1))',
      },
      colors: {
        // OKLCH colors with HEX fallbacks for Safari < 16.4
        primary: 'var(--color-primary, var(--color-primary-fallback, #4f46e5))',
        'primary-light': 'var(--color-primary-light, var(--color-primary-light-fallback, #6366f1))',
        'primary-dark': 'var(--color-primary-dark, var(--color-primary-dark-fallback, #3730a3))',
        secondary: 'var(--color-secondary, var(--color-secondary-fallback, #0ea5e9))',
        'secondary-light': 'var(--color-secondary-light, var(--color-secondary-light-fallback, #38bdf8))',
        'secondary-dark': 'var(--color-secondary-dark, var(--color-secondary-dark-fallback, #0369a1))',
        accent: 'var(--color-accent, var(--color-accent-fallback, #06b6d4))',
        'accent-light': 'var(--color-accent-light, var(--color-accent-light-fallback, #22d3ee))',
        'accent-dark': 'var(--color-accent-dark, var(--color-accent-dark-fallback, #0e7490))',
        success: 'var(--color-success, var(--color-success-fallback, #22c55e))',
        'success-light': 'var(--color-success-light, var(--color-success-light-fallback, #4ade80))',
        'success-dark': 'var(--color-success-dark, var(--color-success-dark-fallback, #15803d))',
        warning: 'var(--color-warning, var(--color-warning-fallback, #facc15))',
        'warning-light': 'var(--color-warning-light, var(--color-warning-light-fallback, #fde047))',
        'warning-dark': 'var(--color-warning-dark, var(--color-warning-dark-fallback, #a16207))',
        error: 'var(--color-error, var(--color-error-fallback, #ef4444))',
        'error-light': 'var(--color-error-light, var(--color-error-light-fallback, #f87171))',
        'error-dark': 'var(--color-error-dark, var(--color-error-dark-fallback, #991b1b))',
        info: 'var(--color-info, var(--color-info-fallback, #0ea5e9))',
        'info-light': 'var(--color-info-light, var(--color-info-light-fallback, #38bdf8))',
        'info-dark': 'var(--color-info-dark, var(--color-info-dark-fallback, #0369a1))',
        surface: 'var(--color-surface, var(--color-surface-fallback, #ffffff))',
        'surface-dark': 'var(--color-surface-dark, var(--color-surface-dark-fallback, #0f172a))',
        'surface-subtle': 'var(--color-surface-subtle, var(--color-surface-subtle-fallback, #eef2ff))',
        'surface-dark-subtle': 'var(--color-surface-dark-subtle, var(--color-surface-dark-subtle-fallback, #111827))',
        background: 'var(--color-background, var(--color-background-fallback, #f8fafc))',
        'background-dark': 'var(--color-background-dark, var(--color-background-dark-fallback, #0b1220))',
        foreground: 'var(--color-foreground, var(--color-foreground-fallback, #111827))',
        'foreground-strong': 'var(--color-foreground-strong, var(--color-foreground-strong-fallback, #0f172a))',
        'foreground-light': 'var(--color-foreground-light, var(--color-foreground-light-fallback, #f9fafb))',
        'muted-foreground': 'var(--color-muted-foreground, var(--color-muted-foreground-fallback, #374151))',
        'subtle-foreground': 'var(--color-subtle-foreground, var(--color-subtle-foreground-fallback, #4b5563))',
        'on-accent': 'var(--color-on-accent, var(--color-on-accent-fallback, #051b2a))',
        'on-primary': 'var(--color-on-primary, var(--color-on-primary-fallback, #ffffff))',
        'on-secondary': 'var(--color-on-secondary, var(--color-on-secondary-fallback, #062433))',
        'on-dark': 'var(--color-on-dark, var(--color-on-dark-fallback, #f9fafb))',
        neutral: 'var(--color-neutral, var(--color-neutral-fallback, #64748b))',
        'neutral-light': 'var(--color-neutral-light, var(--color-neutral-light-fallback, #cbd5e1))',
        'neutral-dark': 'var(--color-neutral-dark, var(--color-neutral-dark-fallback, #334155))',
        border: 'var(--border-color, rgba(15, 23, 42, 0.08))',
        'border-dark': 'var(--border-color-dark, rgba(148, 163, 184, 0.2))',
        // Semantic aliases for clarity (no behavior change)
        'on-surface': 'var(--color-foreground, var(--color-foreground-fallback, #111827))',
        'on-surface-strong': 'var(--color-foreground-strong, var(--color-foreground-strong-fallback, #0f172a))',
      },
      screens: {
        'sm-md': { raw: '(min-width: 651px) and (max-width: 767px)' },
        'supports-backdrop': { raw: '(backdrop-filter: blur(0))' },
      },
      spacing: {
        px: 'var(--space-px)',
        0: 'var(--space-0)',
        0.5: 'var(--space-0\\.5)',
        1: 'var(--space-1)',
        1.5: 'var(--space-1\\.5)',
        2: 'var(--space-2)',
        2.5: 'var(--space-2\\.5)',
        3: 'var(--space-3)',
        3.5: 'var(--space-3\\.5)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        7: 'var(--space-7)',
        8: 'var(--space-8)',
        9: 'var(--space-9)',
        10: 'var(--space-10)',
        11: 'var(--space-11)',
        12: 'var(--space-12)',
        14: 'var(--space-14)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        28: 'var(--space-28)',
        32: 'var(--space-32)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: 'var(--radius-full)',
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        heading: 'var(--font-heading)',
        mono: 'var(--font-mono)',
        ui: 'var(--font-sans)',
      },
      fontSize: {
        xxs: 'var(--fs-xxs)',
        xs: 'var(--fs-xs)',
        sm: 'var(--fs-sm)',
        base: 'var(--fs-base)',
        lg: 'var(--fs-lg)',
        xl: 'var(--fs-xl)',
        '2xl': 'var(--fs-2xl)',
        '3xl': 'var(--fs-3xl)',
        '4xl': 'var(--fs-4xl)',
        '5xl': 'var(--fs-5xl)',
        '6xl': 'var(--fs-6xl)',
        '7xl': 'var(--fs-7xl)',
        '8xl': 'var(--fs-8xl)',
        '9xl': 'var(--fs-9xl)',
      },
      boxShadow: {
        card: 'var(--shadow-card, 0 20px 45px -20px rgba(16, 24, 40, 0.35))',
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
        none: 'var(--shadow-none)',
      },
      backgroundImage: {
        'btn-primary':
          'linear-gradient(135deg, var(--color-primary) 0%, var(--color-primary-dark) 100%)',
        'gradient-primary': 'var(--gradient-primary)',
        'gradient-accent': 'var(--gradient-accent)',
        'gradient-secondary': 'var(--gradient-secondary)',
        'gradient-info': 'var(--gradient-info)',
        'gradient-success': 'var(--gradient-success)',
        'gradient-warning': 'var(--gradient-warning)',
        'gradient-error': 'var(--gradient-error)',
      },
      data: {
        open: 'state=open',
        closed: 'state=closed',
      },

      fontWeight: {
        thin: 'var(--fw-thin)',
        extralight: 'var(--fw-extralight)',
        light: 'var(--fw-light)',
        normal: 'var(--fw-normal)',
        medium: 'var(--fw-medium)',
        semibold: 'var(--fw-semibold)',
        bold: 'var(--fw-bold)',
        extrabold: 'var(--fw-extrabold)',
        black: 'var(--fw-black)',
      },
      letterSpacing: {
        tighter: 'var(--ls-tighter)',
        tight: 'var(--ls-tight)',
        normal: 'var(--ls-normal)',
        wide: 'var(--ls-wide)',
        wider: 'var(--ls-wider)',
        widest: 'var(--ls-widest)',
        label: 'var(--ls-label)',
        smallcaps: 'var(--ls-smallcaps)',
        heading: 'var(--ls-heading)',
        body: 'var(--ls-body)',
      },
      lineHeight: {
        none: 'var(--lh-none)',
        tight: 'var(--lh-tight)',
        snug: 'var(--lh-snug)',
        normal: 'var(--lh-normal)',
        relaxed: 'var(--lh-relaxed)',
        loose: 'var(--lh-loose)',
        heading: 'var(--lh-heading)',
        body: 'var(--lh-body)',
      },
      maxWidth: {
        'container-2xl': 'var(--container-2xl)',
      },
      zIndex: { auto: 'auto', 0: '0', 10: '10', 20: '20', 30: '30', 40: '40', 50: '50' },
      opacity: { 
        0: '0', 
        5: '0.05',
        10: '0.1',
        20: '0.2',
        25: '0.25', 
        30: '0.3',
        40: '0.4',
        50: '0.5',
        60: '0.6',
        70: '0.7',
        75: '0.75', 
        80: '0.8',
        85: '0.85',
        90: '0.9',
        95: '0.95',
        100: '1',
        hover: 'var(--state-hover-opacity)',
        active: 'var(--state-active-opacity)',
        disabled: 'var(--state-disabled-opacity)',
      },
      borderWidth: { 0: '0px', 1: '1px', 2: '2px', 4: '4px', 8: '8px' },

      blur: { sm: 'var(--blur-sm)', DEFAULT: 'var(--blur)', lg: 'var(--blur-lg)' },
      backdropBlur: { sm: 'var(--blur-sm)', DEFAULT: 'var(--blur)', lg: 'var(--blur-lg)' },
      transitionDuration: {
        instant: 'var(--duration-instant)',
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        DEFAULT: 'var(--duration)',
        moderate: 'var(--duration-moderate)',
        slow: 'var(--duration-slow)',
        slower: 'var(--duration-slower)',
        slowest: 'var(--duration-slowest)',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
        emphasized: 'var(--ease-emphasized)',
        decelerate: 'var(--ease-decelerate)',
        accelerate: 'var(--ease-accelerate)',
        'in-quad': 'var(--ease-in-quad)',
        'out-quad': 'var(--ease-out-quad)',
        'in-out-quad': 'var(--ease-in-out-quad)',
        spring: 'var(--ease-spring)',
        bounce: 'var(--ease-bounce)',
      },
      transitionDelay: {
        xs: 'var(--delay-xs)',
        sm: 'var(--delay-sm)',
        md: 'var(--delay-md)',
        lg: 'var(--delay-lg)',
        xl: 'var(--delay-xl)',
      },

      ringWidth: { DEFAULT: '2px', 0: '0px', 1: '1px', 2: '2px', 4: '4px' },
      typography: ({ theme }: { theme: (path: string, fallback?: any) => any }) => ({
        DEFAULT: {
          css: {
            maxWidth: 'none',
            a: {
              color: theme('colors.primary', 'var(--color-primary)'),
              textDecoration: 'underline',
              '&:hover': { color: theme('colors["primary-dark"]', 'var(--color-primary-dark)') },
            },
            h1: { fontSize: theme('fontSize.2xl'), fontWeight: theme('fontWeight.bold') },
            h2: { fontSize: theme('fontSize.xl'), fontWeight: theme('fontWeight.semibold') },
            h3: { fontSize: theme('fontSize.lg'), fontWeight: theme('fontWeight.medium') },
          },
        },
      }),
    },
  },
  plugins: [containerQueries, typography],
};

export default config;
