name = "blakeoxford"
compatibility_date = "2025-05-29"
pages_build_output_dir = "./dist"

[env.production]
kv_namespaces = [
  { binding = "CONTACT_MESSAGES", id = "65439bda285f486f9b07fc2a30bc5099" }
]

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id      = "65439bda285f486f9b07fc2a30bc5099"

[[kv_namespaces]]
binding = "CONTACT_MESSAGES"
id      = "65439bda285f486f9b07fc2a30bc5099"