name: Auto Request Reviewers

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-request reviewers from CODEOWNERS
        uses: necojackarc/auto-request-review@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/auto-request-review.yml
